language: python
python: 3.5
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=./ pytest -s # run unit tests
  - docker build -t antra-bot . # build docker container

jobs:
  include:
    - stage: "install requirements"
      script: pip install -r requirements.txt
    - stage: "unit tests"
      script: PYTHONPATH=./ pytest -s
    - stage: "build container"
      script: docker build -t antra-bot .
    - stage: "deploy container"
      deploy:
        provider: heroku
        app: antrabot
        api_key: $HEROKU_AUTH_TOKEN
#notifications:
#  slack:
#    on_success: change
#    on_failure: always