language: python
python: 3.5
services:
  - docker
install:
  - pip install -r requirements.txt # install libs to run tests
script:
  - PYTHONPATH=./ pytest -s # run unit tests
deploy:
  provider: heroku
  app: antrabot
  api_key: $HEROKU_AUTH_TOKEN
  run: "heroku run ./run.sh"