language: python
python: 3.5
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=./ pytest -s # run unit tests
  - docker build -t antra-bot . # build docker container

#notifications:
#  slack:
#    on_success: change
#    on_failure: always