language: python
python: 3.5
services:
  - docker
jobs:
  include:
    - stage: "install requirements"
      script: pip install -r requirements.txt
    - stage: "unit tests"
      script: PYTHONPATH=./ pytest -s
    - stage: "build container"
      script: docker build -t registry.heroku.com/antra-bot .
    - stage: "deploy container"
      script:
        - docker login -u _ -p "$HEROKU_AUTH_TOKEN"  registry.heroku.com
        - docker push registry.heroku.com/antra-bot
    - stage: "start container"
      script: heroku run --app registry.heroku.com/antra-bot -e TWITCH_USERNAME=$TWITCH_USERNAME -e CLIENT_ID=$CLIENT_ID -e TWITCH_TOKEN=$TWITCH_TOKEN -e CHANNEL=$CHANNEL -e MONGODB_URI=$MONGODB_URI

