language: python
python: 3.5
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=./ pytest -s # run unit tests
deploy:
  provider: heroku
  app: antrabot
  api_key: $HEROKU_AUTH_TOKEN
  run: "heroku run python3 ./antra_bot.py $TWITCH_USERNAME $CLIENT_ID $TWITCH_TOKEN $CHANNEL"
#jobs:
#  include:
#    - stage: "install requirements"
#      script: pip install -r requirements.txt
#    - stage: "unit tests"
#      script: PYTHONPATH=./ pytest -s
#    - stage: "deploy container"
#      deploy:
#        provider: heroku
#        app: antrabot
#        api_key: $HEROKU_AUTH_TOKEN
#        run: python3 ./antra_bot.py $TWITCH_USERNAME $CLIENT_ID $TWITCH_TOKEN $CHANNEL
